name: Cloud check in action
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"
      timezone: "Asia/Shanghai"  # 指定时区
    - cron: "0 10 * * *"
      timezone: "Asia/Shanghai"  # 同上

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Load Secrets
        run: |
          echo "PROD_KEY=${{ secrets.PROD_KEY }}" >> .env
      - name: Install Dependencies
        run: npm install
      - name: Start Application
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm start